### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#11]
The `releaser` action began failing on this commit: https://github.com/ovrclk/helm-charts/commit/144c577501ac3ac4145a76662af616159a6cfdb8

The failure is here: https://github.com/ovrclk/helm-charts/actions/runs/1819142175

**Comment by boz** [comment]
It looks like running a release on commits to `master` causes a name conflict.

Let's stick with the pattern used on our other projects: only release on a version tag (`v*`), and have that tag dictate the version that is released.

**Comment by sacreman** [comment]
It's not well documented and therefore confusing. But how it works is that each pull request needs to bump the chart version in Chart.yaml.

The Github action uses this file change by default to create a new version tag.

It's kind of annoying because I always forget to bump it in the PR.

We could probably automate an increment on PR merge. Or use a linter to fail tests if that file isn't updated.

**Comment by sacreman** [comment]
The linting now will fail on pull requests if the version number isn't bumped in Chart.yaml.
