### ISSUE TITLE
akash-provider: move `run.sh` into a standalone file

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#16]
So that it can be linted and tested outside of a pod.

https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/templates/configmap-boot.yaml#L7-L69

**Comment by ghost** [comment]
Here is a PR https://github.com/ovrclk/helm-charts/pull/41 that moves `run.sh` into a standalone file.

It is till in the form of template though.
Not sure if we want to go beyond this point further and make it entirely non-template-based as one won't be able to test it straight away, unless setting all the environment variables correctly which are also templated here https://github.com/ovrclk/helm-charts/blob/c10fa285da5c72a396e28ad61615632b029048d5/charts/akash-provider/templates/deployment.yaml#L60-L154

`run.sh` is currently having two parts where it needs to be templated:
- provider.yaml file generation (we are passing these via https://github.com/ovrclk/helm-charts/blob/c10fa285da5c72a396e28ad61615632b029048d5/charts/akash-provider/values.yaml#L61-L77 or directly on the CLI via `--set attributes[N].key/value=` arguments) => https://github.com/ovrclk/helm-charts/issues/14
- `/bin/akash tx cert generate server provider.{{ .Values.domain }}`

We could probably use another two template-based configmaps and let `run.sh` script read those files instead, but, I think that will be too over-engineered.

**Upd:**

And, ideally, the docker image should only run `akash provider run` (get configs via the env. variables only), and configmaps only to deliver the config files (`provider.yaml`, etc).
But since this `run.sh` script does more things such as provider attributes update, certificate registration, etc.. these steps should probably really be separated as suggested here https://github.com/ovrclk/helm-charts/issues/9#issuecomment-1045373643
